services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - DEBUG=1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8444:443"  # Changed to 8444:443
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web