# Generated by Django 4.1.7 on 2024-06-17 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audioSrc', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('recordingDate', models.CharField(max_length=200)),
                ('publishDate', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recordings.category')),
            ],
        ),
    ]
