# Generated by Django 4.1.7 on 2024-06-17 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recordings',
            name='recordingDate',
            field=models.DateTimeField(),
        ),
    ]
