# Generated by Django 5.0.6 on 2024-06-17 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_alter_recordings_publishdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nombre',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audioSrc', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('recordingDate', models.DateTimeField()),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('favorite', models.BooleanField(default=False)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recordings.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Recordings',
        ),
    ]
