# Generated by Django 5.0.6 on 2024-06-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_alter_record_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categoria', to='recordings.category'),
        ),
    ]
