# Generated by Django 5.0.6 on 2024-06-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0007_alter_record_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='categoryId',
            new_name='category',
        ),
    ]
