# Generated by Django 5.0.6 on 2024-06-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0008_rename_categoryid_record_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='desc', max_length=200),
            preserve_default=False,
        ),
    ]
