# Generated by Django 5.0.6 on 2024-06-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0014_tag_record_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
    ]
