# Generated by Django 5.0.6 on 2024-06-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0015_rename_name_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='tag', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='recordings', to='recordings.tag'),
        ),
    ]
