# Generated by Django 5.0.6 on 2024-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0016_tag_description_alter_record_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(related_name='recordings', to='recordings.tag'),
        ),
    ]
