# Generated by Django 5.0.6 on 2024-06-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0017_alter_record_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='favorite',
        ),
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
