# Generated by Django 5.0.6 on 2024-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0018_remove_record_favorite_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
