# Generated by Django 5.0.6 on 2024-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0019_alter_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='audioSrc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
