# Generated by Django 5.0.6 on 2024-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0020_alter_record_audiosrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='audioSrc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recordings', to='recordings.tag'),
        ),
    ]
