# Generated by Django 4.1.7 on 2024-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0021_alter_record_audiosrc_alter_record_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
