# Generated by Django 4.1.7 on 2024-06-27 11:00

from django.db import migrations, models
import recordings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0022_record_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/', validators=[recordings.validators.validate_audio_file]),
        ),
    ]
