# Generated by Django 5.0.6 on 2024-06-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0023_alter_record_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/authors'),
        ),
    ]
