# Generated by Django 5.0.6 on 2024-06-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0024_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/record'),
        ),
    ]
