# Generated by Django 5.0.6 on 2024-06-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0025_alter_author_title_alter_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
