# Generated by Django 5.0.6 on 2024-06-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0027_remove_record_audiosrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='lugar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
