# Generated by Django 5.0.6 on 2024-08-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_customuser_favorite_records'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recordings',
            field=models.ManyToManyField(related_name='recordings', to='recordings.record'),
        ),
    ]
