# Generated by Django 5.0.6 on 2024-08-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_customuser_recordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='recordings',
        ),
    ]
